schema.graphql, src/handlers/dkg/dkgMetaData/eventHandler.ts, src/handlers/dkg/dkgMetaData/publicKey.ts, src/types/interfaces.ts, src/types/models/ProposalItem.ts, src/types/models/UnsignedProposalsQueueItem.ts, src/utils/proposals/getCurrentQueues.ts
=> Added timestamp value for json fields

schema.graphql, src/handlers/dkg/dkgMetaData/eventHandler.ts, src/handlers/dkg/dkgMetaData/publicKey.ts, src/handlers/session.ts, src/types/interfaces.ts, src/types/models/ProposalItem.ts, src/types/models/Session.ts, src/types/models/SessionValidator.ts, src/types/models/UnsignedProposalsQueueItem.ts, src/types/models/Validator.ts, src/types/models/index.ts, src/utils/proposals/getCurrentQueues.ts
#Overview
Enhanced the authorities to be an entity
Closes #18
=> Enhanced authorities

project.yaml, schema.graphql, src/handlers/account.ts, src/handlers/session.ts, src/mappings/mappingHandlers.ts, src/types/models/Account.ts
- Fixed the authority's account
- Add identity pallet integration
<details>
<summary>Details</summary>
```json
{
"data": {
"proposers": {
"nodes": [
{
"id": "5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty",
"account": {
"id": "5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty",
"email": null,
"twitter": null,
"countryCode": null
}
},
{
"id": "5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y",
"account": {
"id": "5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y",
"email": null,
"twitter": null,
"countryCode": null
}
},
{
"id": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
"account": {
"id": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
"email": "validator@alice.com",
"twitter": "alice_validator_main",
"countryCode": "EG"
}
}
]
}
}
}
```
</details>
=> Fix authorities account ids and added identity pallet in integrations

src/handlers/dkg/dkgMetaData/eventHandler.ts, src/handlers/dkg/dkgMetaData/handler.ts, src/handlers/dkg/dkgProposals/eventHandler.ts, src/handlers/session.ts
=> Fix session block id

README.md, project.yaml, schema.graphql, src/handlers/dkg/dkgProposalHandler/eventHandler.ts, src/handlers/dkg/dkgProposals/eventHandler.ts, src/handlers/session.ts, src/types/enums.ts, src/types/models/ProposalItem.ts, src/types/models/ProposalVote.ts, src/utils/proposals/getCurrentQueues.ts
Tracking the proposers that didn't commit a vote for a proposal
=> Added abstain votes

.gitignore, README.md, scripts/README.md, scripts/insert-standalone-keys.sh, scripts/start-standalone-local.sh, scripts/start-subql.sh
Changes introduced in this PR:
- Adds scripts to automate local tangle setup for quick development
=> chore: adds scripts to automate setup

project.yaml, src/handlers/dkg/dkgMetaData/types.ts, src/handlers/dkg/dkgProposalHandler/eventHandler.ts, src/handlers/dkg/dkgProposals/eventHandler.ts, src/handlers/session.ts, src/utils/proposals/getCurrentQueues.ts
This PR addresses the issue of subql not being able to index all types of proposals by providing a fix that enables it to do so.
=> Fix proposal types indexing issue

docker-compose.yml, project.yaml, src/constants/index.ts, src/mappings/mappingHandlers.ts
This PR removes the hardcoded session height which we use to perform checks (signature threshold, keygen threshold and authorities) after every new session interval and gets the value from the API.
=> Removes hardcoded session height value

.github/workflows/check-lint.yml, .github/workflows/publish-vanchor-client.yml
Add workflow_dispatch to GA to allow manual trigger
=> Add workflow_dispatch to GA to allow manual trigger

.envrc, .gitignore, flake.lock, flake.nix
- No functional Changes, just adding integrations for Nix and Flakes for easier cross system development.
=> Add Nix and Flakes for devenv

packages/vanchor-client/.graphclient/index.ts, packages/vanchor-client/.graphclient/schema.graphql, packages/vanchor-client/.graphclient/sources/vanchor/introspectionSchema.ts, packages/vanchor-client/.graphclient/sources/vanchor/schema.graphql, packages/vanchor-client/.graphclient/sources/vanchor/types.ts, packages/vanchor-client/.graphclientrc.yml, packages/vanchor-client/src/config.ts, packages/vanchor-client/src/queries/RelayerFee.ts, packages/vanchor-client/src/queries/RelayerFeeHistory.ts, packages/vanchor-client/src/queries/Withdrawal.ts, packages/vanchor-client/src/queries/WithdrawalHistory.ts, packages/vanchor-client/src/queries/WrappingFee.ts, packages/vanchor-client/src/queries/WrappingFeeHistory.ts, packages/vanchor-client/src/queries/deposit/deposit.ts, packages/vanchor-client/src/queries/deposit/deposit15MinsInterval.ts, packages/vanchor-client/src/queries/deposit/depositDayInterval.ts, packages/vanchor-client/src/queries/deposit/queries.graphql, packages/vanchor-client/src/queries/relayerFee.graphql, packages/vanchor-client/src/queries/tvl/queries.graphql, packages/vanchor-client/src/queries/tvl/tvl.ts, packages/vanchor-client/src/queries/tvl/tvl15MinsInterval.ts, packages/vanchor-client/src/queries/tvl/tvlDayInterval.ts, packages/vanchor-client/src/queries/withdrawal.graphql, packages/vanchor-client/src/queries/wrappingFee.graphql
Closed https://github.com/webb-tools/webb-graphql/issues/139.
=> feat: move deposit queries into graphql files

packages/vanchor-client/.graphclient/index.ts, packages/vanchor-client/.graphclient/schema.graphql, packages/vanchor-client/.graphclient/sources/vanchor/introspectionSchema.ts, packages/vanchor-client/.graphclient/sources/vanchor/schema.graphql, packages/vanchor-client/.graphclient/sources/vanchor/types.ts, packages/vanchor-client/.graphclientrc.yml, packages/vanchor-client/src/config.ts, packages/vanchor/configs/chains.prod.toml, packages/vanchor/networks/live.json, packages/vanchor/package.json, packages/vanchor/subgraph.yaml
Closes https://github.com/webb-tools/webb-graphql/issues/120
=> Adding Tangle Testnet to SubGraph backend

packages/dkg/src/handlers/dkg/dkgMetaData/publicKey.ts
Fixes block hash error in ensure key to get the block hash.
=> Fixes block hash error in ensure key

packages/vanchor-client/.graphclient/index.ts, packages/vanchor-client/.graphclient/schema.graphql, packages/vanchor-client/.graphclient/sources/vanchor/introspectionSchema.ts, packages/vanchor-client/.graphclient/sources/vanchor/schema.graphql, packages/vanchor-client/.graphclient/sources/vanchor/types.ts, packages/vanchor-client/src/queries/tvl/tvl.ts, packages/vanchor-client/src/queries/wrappingFee/wrappingFee.ts, packages/vanchor/src/deposit/depositDayInterval.ts
Fix minor bugs related to TVL and deposits
=> fix: fix query bug

packages/dkg/src/handlers/dkg/dkgMetaData/eventHandler.ts, packages/dkg/src/handlers/dkg/dkgMetaData/publicKey.ts
Currently, each public key's history array does not include `Rotated` status in timeline. This PR fixes it by correctly passing update key status method in the correct dkg metadata section's event.
=> Fixes public key rotated timeline not added issue

packages/vanchor/networks/live.json
```
Bridge Address: 0x0447bc20C5360D62e73dB3Ea0bB1848EBbdc5ee6
Anchor Address: 0x9b5404eBc174a7eE36b0d248b2735382B320EC76
Webb Wrapped tTNT (webbtTNT): 0x981d8781bfCCBdB7C9EF2ABbe6DFa791a85f6Ea5
```
=> Update contract addresses to latest deployment

packages/vanchor-client/.graphclient/index.ts, packages/vanchor-client/.graphclient/schema.graphql, packages/vanchor-client/.graphclient/sources/vanchor/introspectionSchema.ts, packages/vanchor-client/.graphclient/sources/vanchor/schema.graphql, packages/vanchor-client/.graphclient/sources/vanchor/types.ts, packages/vanchor-client/src/example-queries.ts, packages/vanchor-client/src/graphql/transaction.graphql, packages/vanchor-client/src/index.ts, packages/vanchor-client/src/queries/transaction/index.ts, packages/vanchor-client/src/queries/transaction/transaction.ts, packages/vanchor/schema.graphql, packages/vanchor/src/relayerFee/relayerFee.ts, packages/vanchor/src/shieldedTransaction.ts, packages/vanchor/src/transaction/index.ts, packages/vanchor/src/transaction/transaction.ts, packages/vanchor/subgraph.yaml
- Add Transaction Log
- Fix error with relayer fees
Closes #146 
Closes #149
=> Add transaction log

packages/dkg/schema.graphql, packages/dkg/src/handlers/account.ts, packages/dkg/src/handlers/dkg/dkgMetaData/eventHandler.ts, packages/dkg/src/handlers/session.ts, packages/dkg/src/mappings/mappingHandlers.ts
- Updates key status when the signature is submitted.
- Adds new method `RecordAuthorityUptime` to record validator uptime.
=> Adds key signed status and optimize uptime calculation

packages/vanchor-client/.graphclient/index.ts, packages/vanchor-client/src/graphql/deposit.graphql, packages/vanchor-client/src/graphql/relayerFee.graphql, packages/vanchor-client/src/graphql/tvl.graphql, packages/vanchor-client/src/graphql/twl.graphql, packages/vanchor-client/src/graphql/volume.graphql, packages/vanchor-client/src/graphql/withdrawal.graphql, packages/vanchor-client/src/graphql/wrappingFee.graphql
The reason for this PR is mentioned [here](https://github.com/webb-tools/webb-dapp/issues/1625#issuecomment-1723443762).
=> Update all queries to get items by range of start intervals

packages/vanchor-client/src/queries/deposit/deposit.ts, packages/vanchor-client/src/queries/deposit/deposit15MinsInterval.ts, packages/vanchor-client/src/queries/deposit/depositDayInterval.ts, packages/vanchor-client/src/queries/relayerFee/relayerFee.ts, packages/vanchor-client/src/queries/relayerFee/relayerFee15MinsInterval.ts, packages/vanchor-client/src/queries/relayerFee/relayerFeeDayInterval.ts, packages/vanchor-client/src/queries/tvl/tvl.ts, packages/vanchor-client/src/queries/tvl/tvl15MinsInterval.ts, packages/vanchor-client/src/queries/tvl/tvlDayInterval.ts, packages/vanchor-client/src/queries/twl/twl.ts, packages/vanchor-client/src/queries/twl/twl15MinsInterval.ts, packages/vanchor-client/src/queries/twl/twlDayInterval.ts, packages/vanchor-client/src/queries/volume/volume.ts, packages/vanchor-client/src/queries/volume/volume15MinsInterval.ts, packages/vanchor-client/src/queries/volume/volumeDayInterval.ts, packages/vanchor-client/src/queries/withdrawal/withdrawal.ts, packages/vanchor-client/src/queries/withdrawal/withdrawal15MinsInterval.ts, packages/vanchor-client/src/queries/withdrawal/withdrawalDayInterval.ts, packages/vanchor-client/src/queries/wrappingFee/wrappingFee.ts, packages/vanchor-client/src/queries/wrappingFee/wrappingFee15MinsInterval.ts, packages/vanchor-client/src/queries/wrappingFee/wrappingFeeDayInterval.ts
- Remove unnecessary async await 
- Update the TVL query to fetch data in parallel
=> Improve SubGraph Queries

packages/dkg/docker-compose.yml, packages/dkg/package.json, packages/dkg/src/handlers/account.ts
- When account not found for imOnlineId, log the error.
- Remove force clean flags in docker-compose.
Closes #163
=> Fix error thrown for account not found for imOnlineId

packages/vanchor/schema.graphql, packages/vanchor/src/address.ts, packages/vanchor/src/shieldedTransaction.ts, packages/vanchor/subgraph.yaml
- Adding the `Address` entity to the Graph backend to index the VAnchor addresses.
=> Adding the `Address` Entity to The Graph Backend

packages/tangle-mainnet/schema.graphql
@drewstone these are all the types I added. Please comment if you find anything is missing or need modification
Related #170
=> Update types in schema

packages/tangle-mainnet/README.md, packages/tangle-mainnet/project.yaml, packages/tangle-mainnet/schema.graphql, packages/tangle-mainnet/src/handlers/account.ts, packages/tangle-mainnet/src/handlers/claim.ts, packages/tangle-mainnet/src/handlers/index.ts, packages/tangle-mainnet/src/handlers/session.ts, packages/tangle-mainnet/src/index.ts, packages/tangle-mainnet/src/mappings/mappingHandlers.ts
- Add Claim Schema
- Fix errors when handling Heartbeats
- Closes #176 
- Closes #174
=> Add Tangle Claim + Fix Heartbeat bugs

.github/workflows/check-lint.yml, .github/workflows/check-tsc.yml, package.json, packages/vanchor-client/package.json, packages/vanchor/package.json, packages/vanchor/tsconfig.json
- Add ts-check on each package
- Add `tsc` check to `check.yml` GH workflow to prevent future type misuse 
Related: #54
=> Add Ts check across packages
